add a check to make sure tests were selected

diff --git a/run_tests b/run_tests
--- a/run_tests
+++ b/run_tests
@@ -48,6 +48,7 @@ function usage()
      $0 -f job -n scheduling
      $0 -f test/unit/job_test.rb -f job_review_ -f '/(subm|worker)/'
 EOF
+  exit 1
 }
 
 function set_env_vars {
@@ -115,7 +116,6 @@ do
      case $OPTION in
          h)
              usage
-             exit 1
              ;;
          n)
              matching_methods=$OPTARG
@@ -130,10 +130,15 @@ do
              ;;
          ?)
              usage
-             exit 1
              ;;
      esac
 done
+
+if [[ "$tests" == "" ]]
+then
+  echo ; echo 'Error: No tests selected.' ; echo
+  usage
+fi
 
 if [[ $run_single == 1 ]]
 then
